AspImpactaBiblioteca/Models/Entities/Autor.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AspImpactaBiblioteca.Models.Entities
{
    public class Autor
    {
        [Key]        
        public int Id { get; set; }
        public string Nome { get; set; }
        public virtual List<Livro> Livros { get; set; }

        // TESTANDO 

    }
}

AspImpactaBiblioteca/Controllers/AutorController.cs
using AspImpactaBiblioteca.Models.Entities;
using AspImpactaBiblioteca.Models.Interfaces;
using Ninject;
using System.Collections.Generic;
using System.Net;
using System.Web.Mvc;

namespace AspImpactaBiblioteca.Controllers
{
    public class AutorController : Controller
    {        
        private readonly IAutorRepository autorRepository;

        [Inject]
        public AutorController(IAutorRepository _autorRepository)
        {            
            autorRepository = _autorRepository;
        }
        
        public ActionResult Index()
        {
            return View();
        }
       
        public ActionResult Listar()
        {            
            return View(autorRepository.ListarTodos());
        }
        
        public ActionResult Create()
        {
            return View();
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Autor autor)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    autorRepository.Adicionar(autor);
                    autorRepository.Salvar();

                    return RedirectToAction("Listar");
                }

                return View(autor);

            }
            catch
            {
                return View();
            }
        }
        
        public ActionResult Edit(int id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            
            return View(autorRepository.BuscarPorId(id));
        }
        
        [HttpPost]
        public ActionResult Edit(Autor autor)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    autorRepository.Atualizar(autor);
                    autorRepository.Salvar();

                    return RedirectToAction("Listar");
                }

                return View(autor);

            }
            catch
            {
                return View();
            }
        }

        [HttpPost]
        public ContentResult Delete(int id)
        {
            autorRepository.ExcluirPorId(id);
            autorRepository.Salvar();

            return Content("Excluído com sucesso");
        }

    }
}

AspImpactaBiblioteca/Views/Autor/Create.cshtml
@model AspImpactaBiblioteca.Models.Entities.Autor

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width" />
        <title>Cadastrar novo Autor</title>

    </head>

    <body>

        <h3>Cadastro de Autor</h3>
        <hr />


        @using (Html.BeginForm("Create", "Autor", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary()

            <div class="row">
                <div class="input-field col s4">
                    <i class="material-icons prefix">event_note</i>                                
                    @Html.EditorFor(a => a.Nome)
                    @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                    @Html.LabelFor(a => a.Nome)                    
                </div>
            </div>

            <div class="form-group">

                <div class="row">
                    <button class="btn waves-effect waves-light" type="submit" name="action">
                        Cadastrar
                        <i class="material-icons right">send</i>
                    </button>

                    @Html.ActionLink("Cancelar", "Listar", "Autor", new { @class = "btn waves-effect waves-light red" })
                </div>
            </div>

        }        

    </body>

</html>

AspImpactaBiblioteca/Views/Autor/Edit.cshtml
@model AspImpactaBiblioteca.Models.Entities.Autor

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Autor</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        @using (Html.BeginForm("Create", "Autor", FormMethod.Post))
        {
            <div class="row">
                <div class="input-field col s4">
                    <i class="material-icons prefix">event_note</i>
                    @Html.EditorFor(a => a.Nome)
                    @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                    @Html.LabelFor(a => a.Nome)
                </div>
            </div>

            <div class="form-group">

                <div class="row">
                    <button class="btn waves-effect waves-light" type="submit" name="action">
                        Salvar alterações
                        <i class="material-icons right">send</i>
                    </button>
                    @Html.ActionLink("Cancelar", "Listar", "Autor", new { @class = "btn waves-effect waves-light red" })

                </div>
            </div>

        }
    </div>
}

AspImpactaBiblioteca/Views/Autor/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <title>Página inicial Autores</title>

    </head>

    <body>
        <h2>Autores</h2>
        <p>
            @Html.ActionLink("Listar", "Listar", "Autor", new { @class = "waves-effect waves-light btn" })
            @Html.ActionLink("Adicionar", "Create", "Autor", new { @class = "waves-effect waves-light blue btn" })
        </p>
        

    </body>

</html>

AspImpactaBiblioteca/Views/Autor/Listar.cshtml
@model IEnumerable<AspImpactaBiblioteca.Models.Entities.Autor>

@{
    ViewBag.Title = "Listar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <meta charset="utf-8" />
        <title>Lista de Autores</title>

    </head>

    <body>

        <p>@Html.ActionLink("Novo", "Create", "Autor", new { @class = "waves-effect waves-light btn" })</p>

        @using (Html.BeginForm(null, null, FormMethod.Post))
        {
            @Html.AntiForgeryToken()

            <table id="__AjaxAntiForgeryForm" class="responsive-table table">
                <thead>
                    <tr>
                        <th>@Html.DisplayNameFor(a => a.Id)</th>
                        <th>@Html.DisplayNameFor(a => a.Nome)</th>
                        <th></th>
                    </tr>
                </thead>

                @foreach (var item in Model)
                {

                    <tbody>
                        <tr>
                            <td>@item.Id</td>
                            <td>@item.Nome</td>

                            <td>
                                <a href="@Url.Action("Edit", "Autor", new { id = item.Id })" class="btn-floating btn-small waves-effect waves-light yellow icones tooltipped" data-position="top" data-delay="40" data-tooltip="EDITAR"><i class="material-icons">edit</i></a>
                                <a href="#modalExcluirAutor" class="excluirAutor btn-floating btn-small waves-effect waves-light red icones modal-trigger" data-id="@item.Id"><i class="material-icons">delete</i></a>
                            </td>
                        </tr>
                    </tbody>

                }

            </table>


        }

        <div id="modalExcluirAutor" class="modal">
            <div class="modal-content">
                <h4>Excluir este Autor?</h4>
                <p>Ao remover este item, você não poderá recuperá-lo.</p>
            </div>

            <div class="modal-footer">

                @Html.AntiForgeryToken()
                <button type="button" href="#!" class="modal-action modal-close waves-effect waves-red btn-flat">Cancelar</button>
                <button id="btnConfirmarExclusaoAutor" type="button" class="modal-action modal-close waves-effect waves-green btn-flat">Confirmar</button>

            </div>
        </div>

    </body>

</html>