AspImpactaBiblioteca/Models/Entities/Livro.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace AspImpactaBiblioteca.Models.Entities
{
    public class Livro
    {
        [Key]        
        public int Id { get; set; }

        [StringLength(100)]
        [DisplayName("Nome do livro")]
        public string Nome { get; set; }

        [DisplayName("Quantidade de páginas")]
        public int TotalPaginas { get; set; }

        [DisplayName("Descrição")]
        public string Descricao { get; set; }

        public int Quantidade { get; set; }

        [ForeignKey("CategoriaId")]
        public virtual Categoria Categoria { get; set; }

        [ForeignKey("AutorId")]
        public virtual Autor Autor { get; set; }

        public int CategoriaId { get; set; }

        public int AutorId { get; set; }

        

    }
}

AspImpactaBiblioteca/Controllers/LivroController.cs
using AspImpactaBiblioteca.Helpers.Interfaces;
using AspImpactaBiblioteca.Models.Entities;
using AspImpactaBiblioteca.Models.Interfaces;
using Ninject;
using System.Collections.Generic;
using System.Net;
using System.Web.Mvc;

namespace AspImpactaBiblioteca.Controllers
{
    public class LivroController : Controller
    {        
        private readonly ILivroRepository livroRepository;
        private readonly IRetornaSelectListItemRepository retornaSelectListItemRepository;

        [Inject]
        public LivroController(ILivroRepository _livroRepository, IRetornaSelectListItemRepository _retornaSelectListItemRepository)
        {
            livroRepository = _livroRepository;
            retornaSelectListItemRepository = _retornaSelectListItemRepository;
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Listar()
        {            
            return View(livroRepository.ListarTodos());
        }
        
        public ActionResult Details(int id)
        {            
            return View(livroRepository.BuscarPorId(id));
        }
        
        public ActionResult Create()
        {
            ViewBag.Autores = retornaSelectListItemRepository.Autores();
            ViewBag.Categorias = retornaSelectListItemRepository.Categorias();

            return View();
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Livro livro)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    livroRepository.Adicionar(livro);
                    livroRepository.Salvar();        

                    return RedirectToAction("Listar");
                }

                return View(livro);

            }
            catch
            {
                return View();
            }
        }
        
        public ActionResult Edit(int id)
        {
            if(id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }            

            ViewBag.AutoresEditar = retornaSelectListItemRepository.Autores();
            ViewBag.CategoriasEditar = retornaSelectListItemRepository.Categorias();
                        
            return View(livroRepository.BuscarPorId(id));
        }
        
        [HttpPost]
        public ActionResult Edit(Livro livro)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    livroRepository.Atualizar(livro);
                    livroRepository.Salvar();

                    return RedirectToAction("Listar");
                }

                ViewBag.AutoresEditar = retornaSelectListItemRepository.Autores();
                ViewBag.CategoriasEditar = retornaSelectListItemRepository.Categorias();

                return View(livro);                
            }
            catch
            {
                return View();
            }
        }
        
        [HttpPost]
        public ContentResult Delete(int id)
        {
            livroRepository.ExcluirPorId(id);
            livroRepository.Salvar();

            return Content("Excluído com sucesso");
        }        
      
    }
}

AspImpactaBiblioteca/Views/Livro/Create.cshtml
@model AspImpactaBiblioteca.Models.Entities.Livro

@{
    ViewBag.Title = "Cadastro de livros";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Cadastro de Livro</h2>



@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary()

    <div class="row">

        <h4>Novo Livro</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="row">
            <div class="input-field col s6">
                <i class="material-icons prefix">event_note</i>
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "library_books" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "active" })
            </div>
        </div>

        <div class="row">
            <div class="input-field col s6">
                <i class="material-icons prefix">description</i>
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "library_books" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
                @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "active" })
            </div>
        </div>
               
        <div class="row">
            <div class="input-field col s6">
                <i class="material-icons prefix">library_books</i>
                @Html.EditorFor(model => model.Quantidade, new { htmlAttributes = new { @class = "library_books" } })
                @Html.ValidationMessageFor(model => model.Quantidade, "", new { @class = "text-danger" })
                @Html.LabelFor(model => model.Quantidade, htmlAttributes: new { @class = "active" })
            </div>
        </div>

        <div class="row">
            <div class="input-field col s6">
                <i class="material-icons prefix">import_contacts</i>
                @Html.EditorFor(model => model.TotalPaginas, new { htmlAttributes = new { @class = "library_books" } })
                @Html.ValidationMessageFor(model => model.TotalPaginas, "", new { @class = "text-danger" })
                @Html.LabelFor(model => model.TotalPaginas, htmlAttributes: new { @class = "active" })
            </div>
        </div>

        <div class="row">
            <div class="input-field col s6">
                <i class="material-icons prefix">person_outline</i>
                @Html.DropDownListFor(model => model.AutorId, new SelectList(ViewBag.Autores, "Value", "Text"), "Selecione um Autor")
            </div>
        </div>

        <div class="row">
            <div class="input-field col s6">
                <i class="material-icons prefix">content_paste</i>
                @Html.DropDownListFor(model => model.CategoriaId, new SelectList(ViewBag.Categorias, "Value", "Text"), "Selecione uma Categoria")
            </div>
        </div>

   


        <div class="form-group">
            <button class="btn waves-effect waves-light" type="submit" name="action">
                Cadastrar
                <i class="material-icons right">send</i>
            </button>

            @Html.ActionLink("Cancelar", "Listar", "Livro", new { @class = "btn waves-effect waves-light red" })
        </div>


    </div>
}

AspImpactaBiblioteca/Views/Livro/Details.cshtml
@model AspImpactaBiblioteca.Models.Entities.Livro


@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Detalhes</h2>

<b>@Html.DisplayNameFor(model => model.Nome)</b> <br />
@Model.Nome

<br /><br />

<b>@Html.DisplayNameFor(model => model.Descricao)</b> <br />
@Model.Descricao

<br /><br />

<b>@Html.DisplayNameFor(model => model.Quantidade)</b> <br />
@Model.Quantidade

<br /><br />

<b>@Html.DisplayNameFor(model => model.TotalPaginas)</b> <br />
@Model.TotalPaginas

<br /><br />
<a class="waves-effect waves-light btn-small" href="@Url.Action("Listar", "Livro")">Voltar</a>
<a class="btn-floating btn-small waves-effect waves-light red" href="@Url.Action("Edit", "Livro", new { @id= Model.Id })"><i class="material-icons">edit</i></a>

AspImpactaBiblioteca/Views/Livro/Edit.cshtml
@model AspImpactaBiblioteca.Models.Entities.Livro

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<h2>Editar Livro</h2>



@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()


    <div class="row">

        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="row">
            <div class="input-field col s6">
                <i class="material-icons prefix">event_note</i>
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "library_books" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "active" })
            </div>
        </div>

        <div class="row">
            <div class="input-field col s6">
                <i class="material-icons prefix">description</i>
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "library_books" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
                @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "active" })
            </div>
        </div>

        <div class="row">
            <div class="input-field col s6">
                <i class="material-icons prefix">library_books</i>
                @Html.EditorFor(model => model.Quantidade, new { htmlAttributes = new { @class = "library_books" } })
                @Html.ValidationMessageFor(model => model.Quantidade, "", new { @class = "text-danger" })
                @Html.LabelFor(model => model.Quantidade, htmlAttributes: new { @class = "active" })
            </div>
        </div>

        <div class="row">
            <div class="input-field col s6">
                <i class="material-icons prefix">import_contacts</i>
                @Html.EditorFor(model => model.TotalPaginas, new { htmlAttributes = new { @class = "library_books" } })
                @Html.ValidationMessageFor(model => model.TotalPaginas, "", new { @class = "text-danger" })
                @Html.LabelFor(model => model.TotalPaginas, htmlAttributes: new { @class = "active" })
            </div>
        </div>

        <div class="row">
            <div class="input-field col s6">
                <i class="material-icons prefix">person_outline</i>
                @Html.DropDownListFor(model => model.AutorId, new SelectList(ViewBag.AutoresEditar, "Value", "Text"), "Selecione um Autor")
            </div>
        </div>

        <div class="row">
            <div class="input-field col s6">
                <i class="material-icons prefix">content_paste</i>
                @Html.DropDownListFor(model => model.CategoriaId, new SelectList(ViewBag.CategoriasEditar, "Value", "Text"), "Selecione uma Categoria")
            </div>
        </div>
        


        <div class="form-group">
            <button class="btn waves-effect waves-light" type="submit" name="action">
                Salvar alterações
                <i class="material-icons right">send</i>
            </button>

            @Html.ActionLink("Cancelar", "Listar", "Livro", new { @class = "waves-effect waves-light btn red" })            
        </div>


    </div>

}

AspImpactaBiblioteca/Views/Livro/Index.cshtml
@{
    Layout = Layout;
}

<!DOCTYPE html>

<html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <title>Página inicial Livros</title>
    
    </head>

    <body>
        <h2>Livros</h2>
        <p>
            @Html.ActionLink("Listar", "Listar", "Livro", null, new { @class= "waves-effect waves-light btn" })
            @Html.ActionLink("Adicionar", "Create", "Livro", null, new { @class = "waves-effect waves-light blue btn" })
        </p>      
   

   

    </body>
</html>

AspImpactaBiblioteca/Views/Livro/Listar.cshtml
@model IEnumerable<AspImpactaBiblioteca.Models.Entities.Livro>

@{
    Layout = Layout;
}

<!DOCTYPE html>

<html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <title>Index</title>

    </head>

    <body>
        <p>
            @Html.ActionLink("novo", "Create", null, new { @class = "waves-effect waves-light btn " })
        </p>

        @using (Html.BeginForm(null, null, FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            <table id="_AjaxAntiForgeryForm" class="table">
                <thead>
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.Nome)</th>
                        <th>@Html.DisplayNameFor(model => model.Descricao)</th>
                        <th>@Html.DisplayNameFor(model => model.Quantidade)</th>
                        <th></th>

                    </tr>
                </thead>

                <tbody>

                    @foreach (var item in Model)
                {
                        <tr>
                            <td>@Html.DisplayFor(model => item.Nome)</td>
                            <td>@Html.DisplayFor(model => item.Descricao)</td>
                            <td>@Html.DisplayFor(model => item.Quantidade)</td>

                            <td>
                                <a href="@Url.Action("Edit", "Livro", new { id = item.Id })" class="btn-floating btn-small waves-effect waves-light red icones"><i class="material-icons">edit</i></a>
                                <a href="@Url.Action("Details", "Livro", new { id = item.Id })" class="btn-floating btn-small waves-effect waves-light yellow icones"><i class="material-icons">details</i></a>
                                <a class="excluirLivro btn-floating btn-small waves-effect waves-light blue icones" data-id="@item.Id"><i class="material-icons">delete</i></a>
                                <!--<a href="Url.Action("Delete", "Livro", new { id = item.Id })" class="btn-floating btn-small waves-effect waves-light blue icones right-align"><i class="material-icons">delete</i></a>-->
                            </td>
                        </tr>
                    }

                </tbody>
            </table>

        }

        <div id="modalExcluir" class="modal">
            <div class="modal-content">
                <h4>Excluir este livro?</h4>     
                <p>Ao excluir este item, você não poderá recuperá-lo.</p>
            </div>

            <div class="modal-footer">
                @Html.AntiForgeryToken()
                <button type="button" href="#!" class="modal-action modal-close waves-effect waves-red btn-flat">Cancelar</button>               
                <button type="button" id="btnConfirmarExclusao" class="modal-action modal-close waves-effect waves-green btn-flat">Confirmar</button>
            </div>
        </div>


    </body>
</html>